name: "Employer Of The Month"
description: "Add the 🐶 of the month to your wiki"
branding:
  icon: 'award'
  color: 'green'
inputs:
  tag-to-search:
    description: "Tag to search for your employee"
    required: true
    default: "dog"
  title:
    description: "Perfect title to price your employee"
    required: true
    default: "✨✨ Employee of the month ✨✨"
  page:
    description: "The wiki page you would like to update"
    required: true
    default: "Home.md"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.tag-to-search }}
    - ${{ inputs.title }}
    - ${{ inputs.page }}
